import Login from "@/components/Login";
import { SessionProvider } from "@/components/SessionProvider";
import SideBar from "@/components/SideBar";
import { getServerSession } from "next-auth";
import "../styles/globals.css";
import { authOptions } from "../pages/api/auth/[...nextauth]";
import ClientProvider from "@/components/ClientProvider";
import { Bars3Icon } from "@heroicons/react/24/outline";

export const metadata = {
    title: "ChatGPT Messenger",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await getServerSession(authOptions);

    return (
        <html lang="en">
            <head />
            <body>
                <SessionProvider session={session}>
                    {!session ? (
                        <Login />
                    ) : (
                        <div className="flex">
                            <div className="bg-[#202123] max-w-xs min-w-[10rem] h-screen overflow-y-auto hidden sm:block">
                                <SideBar />
                            </div>

                            <ClientProvider />

                            <div className="bg-[#343541] flex-1">
                                {children}
                            </div>
                        </div>
                    )}
                </SessionProvider>
            </body>
        </html>
    );
}
